// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pheidi.Blazor.Data;

#nullable disable

namespace Pheidi.Blazor.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260313110837_AddTier2Features")]
    partial class AddTier2Features
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("Pheidi.Common.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaidUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShareToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Pheidi.Common.Models.InjuryReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BodyPart")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("InjuryReports");
                });

            modelBuilder.Entity("Pheidi.Common.Models.NewTrainingPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgressionPattern")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaceGoalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShareToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RaceGoalId");

                    b.ToTable("TrainingPlans");
                });

            modelBuilder.Entity("Pheidi.Common.Models.OtpCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email", "Code");

                    b.ToTable("OtpCodes");
                });

            modelBuilder.Entity("Pheidi.Common.Models.PainEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("InjuryReportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InjuryReportId");

                    b.ToTable("PainEntries");
                });

            modelBuilder.Entity("Pheidi.Common.Models.RaceGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomPlanWeeks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Distance")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RaceDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TargetTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RaceGoal");
                });

            modelBuilder.Entity("Pheidi.Common.Models.ScheduledWorkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ActualDistanceMiles")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ActualDuration")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActualEffort")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActualIntensityZone")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompletionPercent")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CoolDownDuration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Feedback")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRunWalk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Modifier")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReadinessScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RunMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TargetDistanceMiles")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TargetDuration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainingWeekId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WalkMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("WarmUpDuration")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrainingWeekId");

                    b.ToTable("ScheduledWorkouts");
                });

            modelBuilder.Entity("Pheidi.Common.Models.TrainingWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainingPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrainingPlanId");

                    b.ToTable("TrainingWeeks");
                });

            modelBuilder.Entity("Pheidi.Common.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvailableDays")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CurrentWeeklyMileage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExperienceLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PacePreference")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreferredLongRunDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RunWalkRunMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RunWalkWalkMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RunningExperienceMonths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransitionTimePreset")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseMiles")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("VdotValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("VolumeMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Pheidi.Common.Models.NewTrainingPlan", b =>
                {
                    b.HasOne("Pheidi.Common.Models.RaceGoal", "RaceGoal")
                        .WithMany()
                        .HasForeignKey("RaceGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RaceGoal");
                });

            modelBuilder.Entity("Pheidi.Common.Models.PainEntry", b =>
                {
                    b.HasOne("Pheidi.Common.Models.InjuryReport", null)
                        .WithMany("PainHistory")
                        .HasForeignKey("InjuryReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pheidi.Common.Models.ScheduledWorkout", b =>
                {
                    b.HasOne("Pheidi.Common.Models.TrainingWeek", null)
                        .WithMany("Workouts")
                        .HasForeignKey("TrainingWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Pheidi.Common.Models.PaceZone", "PaceZone", b1 =>
                        {
                            b1.Property<int>("ScheduledWorkoutId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("RpeDescription")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("PaceZone_RpeDescription");

                            b1.Property<int?>("RpeMax")
                                .HasColumnType("INTEGER")
                                .HasColumnName("PaceZone_RpeMax");

                            b1.Property<int?>("RpeMin")
                                .HasColumnType("INTEGER")
                                .HasColumnName("PaceZone_RpeMin");

                            b1.Property<int>("Zone")
                                .HasColumnType("INTEGER")
                                .HasColumnName("PaceZone_Zone");

                            b1.HasKey("ScheduledWorkoutId");

                            b1.ToTable("ScheduledWorkouts");

                            b1.WithOwner()
                                .HasForeignKey("ScheduledWorkoutId");
                        });

                    b.Navigation("PaceZone");
                });

            modelBuilder.Entity("Pheidi.Common.Models.TrainingWeek", b =>
                {
                    b.HasOne("Pheidi.Common.Models.NewTrainingPlan", null)
                        .WithMany("Weeks")
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pheidi.Common.Models.InjuryReport", b =>
                {
                    b.Navigation("PainHistory");
                });

            modelBuilder.Entity("Pheidi.Common.Models.NewTrainingPlan", b =>
                {
                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("Pheidi.Common.Models.TrainingWeek", b =>
                {
                    b.Navigation("Workouts");
                });
#pragma warning restore 612, 618
        }
    }
}
